global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: redpanda
    metrics_path: /public_metrics
    static_configs:
      - targets:
          - redpanda:9644

  - job_name: sink
    metrics_path: /metrics
    static_configs:
      - targets:
          - sink:4195

  - job_name: cdc-metrics
    metrics_path: /metrics
    static_configs:
      - targets:
          - cdc-metrics:8000
